name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install server deps
        run: npm install --prefix server
      - name: Build server
        run: npm run build --prefix server
      - name: Install web deps
        run: npm install --prefix web
      - name: Build web
        run: npm run build --prefix web
